# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d736ac0819e70250e3871eb5220c64dc21f87af25e38f417bc1a905834a43f0e884b8daa622ace8a27289e4283ae93b11f75815ce7e22427167d0eba8fd714d

test:
  secret_key_base: 1bb72928946fcb8279cb1c22c8574634f5c7b6d344c3d107237d8b95be8408cba7517d7fc7748d13e9de99fa56e80a56763241123f967b30b08a1a36cd0a1566

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
